On branch main

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   README.md
	new file:   _dev/.gitignore
	new file:   _dev/db/db-create-UserAndDB.sh
	new file:   _dev/db/db-functions.py
	new file:   _dev/db/db-populate.py
	new file:   _dev/db/db-railway-createDB.sh
	new file:   _dev/db/db-scripts.py
	new file:   _dev/db/dbvars-createupdate.py
	new file:   _dev/db/dbvars-lg.sh
	new file:   _dev/db/old/db_init.py
	new file:   _dev/db/old/dbvars-byza-railway-ecu.json
	new file:   _dev/db/old/dbvars-byza-railway.json
	new file:   _dev/db/old/dbvars-byza-railway.sh
	new file:   _dev/db/old/old-dbvars-byza-railway.sh
	new file:   _dev/db/old/source-dbvars.py
	new file:   _dev/db/zenv
	new file:   _dev/dbvars-byza-railway.sh
	new file:   _dev/dbvars-lg.sh
	new file:   _dev/dbvars-logitrans-railway.sh
	new file:   _dev/migration/.gitignore
	new file:   _dev/migration/back-bot_migration.py
	new file:   _dev/migration/bot_codebin.py
	new file:   _dev/migration/bot_downloading.py
	new file:   _dev/migration/bot_migration.py
	new file:   _dev/migration/bot_migration_docs.py
	new file:   _dev/migration/cpis.log
	new file:   _dev/migration/dblg.sh
	new file:   _dev/migration/dbvars-lg.sh
	new file:   _dev/migration/dvenv
	new file:   _dev/migration/ecuapass_bot.py
	new file:   _dev/migration/ecuapassdocs
	new file:   _dev/migration/mcis.log
	new file:   _dev/predictions/TextClusterEncoder.py
	new file:   _dev/predictions/csvs/data-byza-cartaportes-cleaned.csv
	new file:   _dev/predictions/csvs/data-byza-cartaportes.csv
	new file:   _dev/predictions/dbvars-lg.sh
	new file:   _dev/predictions/dvenv
	new file:   _dev/predictions/ecuapassdocs
	new file:   _dev/predictions/predictions.py
	new file:   _dev/predictions/predictions_cartaportes.py
	new file:   _dev/predictions/predictions_cpis_mcis.py
	new file:   _dev/scraping/bot_scraping.py
	new file:   _dev/scraping/bot_scraping_codebin.py
	new file:   _dev/scraping/ecuapass_doc.py
	new file:   _dev/scraping/ecuapass_server.py
	new file:   _dev/scraping/org_bot_codebin.py
	new file:   _dev/scripts/bot/TEST-BYZA-CPI-CO7249-DOCFIELDS.json
	new file:   _dev/scripts/bot/TEST-BYZA-CPI-CO7249.pdf
	new file:   _dev/scripts/bot/bot_typedoc.py
	new file:   _dev/scripts/bot/ecuapassdocs
	new file:   _dev/scripts/bot/geckodriver.log
	new file:   _dev/scripts/bot/test.py
	new file:   _dev/scripts/bot/venv
	new file:   _dev/scripts/bot/xvenv
	new file:   _dev/vars/dbvars-byza-railway-ORG.sh
	new file:   _dev/vars/dbvars-byza-railway.json
	new file:   _dev/vars/dbvars-byza-railway.sh
	new file:   _dev/vars/dbvars-createupdate.py
	new file:   _dev/vars/dbvars-lg-ORG.sh
	new file:   _dev/vars/dbvars-lg.sh
	new file:   _dev/vars/dbvars-logitrans-railway.json
	new file:   _dev/vars/dbvars-logitrans-railway.sh
	new file:   _dev/venv
	new file:   _docs/Ecuapassdocs-DevManual-lyx23.lyx~
	new file:   _docs/Ecuapassdocs-DevManual.lyx
	new file:   _docs/Ecuapassdocs-DevManual.lyx~
	new file:   _docs/django-subdomains/django-subdomains-deployment-deepseek.pdf
	new file:   _docs/reqs/reqs-logitrans-01-Oct.lyx
	new file:   _docs/uml-diagram/EcuapassDocs-Diagrama-Modelos-V0-Nov20.pdf
	new file:   _docs/uml-diagram/EcuapassDocs-Diagrama-Modelos-V0.dia
	new file:   _docs/uml-diagram/EcuapassDocs-Diagrama-Modelos-V02.pdf
	new file:   _docs/uml-diagram/EcuapassDocs-Diagrama-Modelos-V03.pdf
	new file:   _docs/uml-diagram/EcuapassDocs-Diagrama-Modelos-V04.pdf
	new file:   _docs/uml-diagram/EcuapassDocs-Diagrama-Modelos-V05.pdf
	new file:   app/Procfile
	new file:   app/README.md
	new file:   app/app_cartaporte/TextClusterEncoder.py
	new file:   app/app_cartaporte/__init__.py
	new file:   app/app_cartaporte/admin.py
	new file:   app/app_cartaporte/apps.py
	new file:   app/app_cartaporte/empresas_cpi.py
	new file:   app/app_cartaporte/listing_cpi.py
	new file:   app/app_cartaporte/middleware.py
	new file:   app/app_cartaporte/models_cpi.py
	new file:   app/app_cartaporte/predictor.py
	new file:   app/app_cartaporte/templates/app_cartaporte/cartaporte_confirm_delete.html
	new file:   app/app_cartaporte/templates/app_cartaporte/cartaporte_detail.html
	new file:   app/app_cartaporte/templates/app_cartaporte/cartaporte_listado_no-links.html
	new file:   app/app_cartaporte/templates/app_cartaporte/old_cartaporte_listado.html
	new file:   app/app_cartaporte/test.py
	new file:   app/app_cartaporte/tests.py
	new file:   app/app_cartaporte/urls_cpi.py
	new file:   app/app_cartaporte/views_CartaporteDocView.py
	new file:   app/app_cartaporte/views_CartaportePredictions.py
	new file:   app/app_cartaporte/views_cpi.py
	new file:   app/app_declaracion/__init__.py
	new file:   app/app_declaracion/admin.py
	new file:   app/app_declaracion/apps.py
	new file:   app/app_declaracion/listing_dti.py
	new file:   app/app_declaracion/models_dti.py
	new file:   app/app_declaracion/templates/app_declaracion/declaracion_confirm_delete.html
	new file:   app/app_declaracion/templates/app_declaracion/declaracion_detail.html
	new file:   app/app_declaracion/templates/app_declaracion/declaracion_form.html
	new file:   app/app_declaracion/templates/app_declaracion/declaracion_listado.html
	new file:   app/app_declaracion/tests.py
	new file:   app/app_declaracion/urls_dti.py
	new file:   app/app_declaracion/views_DeclaracionDocView.py
	new file:   app/app_declaracion/views_dti.py
	new file:   app/app_docs/__init__.py
	new file:   app/app_docs/admin.py
	new file:   app/app_docs/apps.py
	new file:   app/app_docs/docs_DocEcuapass.py
	new file:   app/app_docs/docutils.py
	new file:   app/app_docs/forms_docs.py
	new file:   app/app_docs/listing_doc.py
	new file:   app/app_docs/listing_entities.py
	new file:   app/app_docs/models_EcuapassDoc.py
	new file:   app/app_docs/models_Entidades.py
	new file:   app/app_docs/models_Scripts.py
	new file:   app/app_docs/models_docs.py
	new file:   app/app_docs/pdfcreator.py
	new file:   app/app_docs/sessioninfo.py
	new file:   app/app_docs/static/.gitignore
	new file:   app/app_docs/static/app_docs/css/command_buttons.css
	new file:   app/app_docs/static/app_docs/css/documento_forma_styles.css
	new file:   app/app_docs/static/app_docs/css/styles.34e75460ace7.css
	new file:   app/app_docs/static/app_docs/css/styles.css
	new file:   app/app_docs/static/app_docs/images/icon-image-cartaporte.png
	new file:   app/app_docs/static/app_docs/images/icon-image-declaracion.png
	new file:   app/app_docs/static/app_docs/images/icon-image-manifiesto.png
	new file:   app/app_docs/static/app_docs/images/image-cartaporte-vacia-SILOG-BYZA.png
	new file:   app/app_docs/static/app_docs/images/image-declaracion-vacia-NTA.png
	new file:   app/app_docs/static/app_docs/images/image-manifiesto-vacio-NTA-BYZA.png
	new file:   app/app_docs/static/app_docs/images/image-manifiesto-vacio-NTA.0f3b6b9781ec.png
	new file:   app/app_docs/static/app_docs/js/autocomplete-documents.js
	new file:   app/app_docs/static/app_docs/js/autosave.js
	new file:   app/app_docs/static/app_docs/js/createInputTextareas.js
	new file:   app/app_docs/static/app_docs/js/enable_disable_doc_buttons.js
	new file:   app/app_docs/static/app_docs/js/handleInput.js
	new file:   app/app_docs/static/app_docs/js/handlePredictions.js
	new file:   app/app_docs/static/app_docs/js/loadInputParameters.js
	new file:   app/app_docs/static/app_docs/js/setParametersToInputs.js
	new file:   app/app_docs/static/app_docs/js/utils.js
	new file:   app/app_docs/static/app_docs/json/ecuapassdocs-info.json
	new file:   app/app_docs/templates/app_docs/cliente_confirm_delete.html
	new file:   app/app_docs/templates/app_docs/cliente_detail.html
	new file:   app/app_docs/templates/app_docs/cliente_form.html
	new file:   app/app_docs/templates/app_docs/cliente_list.html
	new file:   app/app_docs/templates/app_docs/conductor_confirm_delete.html
	new file:   app/app_docs/templates/app_docs/conductor_detail.html
	new file:   app/app_docs/templates/app_docs/conductor_form.html
	new file:   app/app_docs/templates/app_docs/conductor_list.html
	new file:   app/app_docs/templates/app_docs/listing_entities.html
	new file:   app/app_docs/templates/app_docs/old/cartaporte_form.html
	new file:   app/app_docs/templates/app_docs/old/cartaporte_list.html
	new file:   app/app_docs/templates/app_docs/vehiculo_confirm_delete.html
	new file:   app/app_docs/templates/app_docs/vehiculo_detail.html
	new file:   app/app_docs/templates/app_docs/vehiculo_form.html
	new file:   app/app_docs/templates/app_docs/vehiculo_list.html
	new file:   app/app_docs/tests.py
	new file:   app/app_docs/urls_docs.py
	new file:   app/app_docs/views_Autocomplete.py
	new file:   app/app_docs/views_EcuapassDocView.py
	new file:   app/app_docs/views_Filters.py
	new file:   app/app_docs/views_docs.py
	new file:   app/app_main/__init__.py
	new file:   app/app_main/asgi.py
	new file:   app/app_main/hosts.py
	new file:   app/app_main/settings.py
	new file:   app/app_main/urls.py
	new file:   app/app_main/views_main.py
	new file:   app/app_main/wsgi.py
	new file:   app/app_manifiesto/__init__.py
	new file:   app/app_manifiesto/admin.py
	new file:   app/app_manifiesto/apps.py
	new file:   app/app_manifiesto/forms_mci.py
	new file:   app/app_manifiesto/listing_mci.py
	new file:   app/app_manifiesto/models_mci.py
	new file:   app/app_manifiesto/tables_mci.py
	new file:   app/app_manifiesto/templates/app_manifiesto/manifiesto_confirm_delete.html
	new file:   app/app_manifiesto/templates/app_manifiesto/manifiesto_detail.html
	new file:   app/app_manifiesto/templates/app_manifiesto/manifiesto_form.html
	new file:   app/app_manifiesto/tests.py
	new file:   app/app_manifiesto/urls_mci.py
	new file:   app/app_manifiesto/views_ManifiestoDocView.py
	new file:   app/app_manifiesto/views_mci.py
	new file:   app/app_usuarios/__init__.py
	new file:   app/app_usuarios/admin-ORG.py
	new file:   app/app_usuarios/admin.py
	new file:   app/app_usuarios/apps.py
	new file:   app/app_usuarios/forms.py
	new file:   app/app_usuarios/management/__init__.py
	new file:   app/app_usuarios/management/commands/__init__.py
	new file:   app/app_usuarios/management/commands/create_tenant.py
	new file:   app/app_usuarios/management/commands/delete_tenant.py
	new file:   app/app_usuarios/management/commands/list_tenants.py
	new file:   app/app_usuarios/models.py
	new file:   app/app_usuarios/tables.py
	new file:   app/app_usuarios/templates/appusuarios/account_created.html
	new file:   app/app_usuarios/templates/appusuarios/base.html
	new file:   app/app_usuarios/templates/appusuarios/base_usuarios.html
	new file:   app/app_usuarios/templates/appusuarios/home.html
	new file:   app/app_usuarios/templates/appusuarios/login-org.html
	new file:   app/app_usuarios/templates/appusuarios/logout-org.html
	new file:   app/app_usuarios/templates/appusuarios/user_create.html
	new file:   app/app_usuarios/templates/back/base_usuarios.html
	new file:   app/app_usuarios/templates/back/login.html
	new file:   app/app_usuarios/templates/back/logout-post.html
	new file:   app/app_usuarios/templates/back/logout.html
	new file:   app/app_usuarios/templates/back/password_change_form.html
	new file:   app/app_usuarios/templates/back/registration-org.html
	new file:   app/app_usuarios/templates/back/registration.html
	new file:   app/app_usuarios/templates/back/user_delete.html
	new file:   app/app_usuarios/templates/back/user_list.html
	new file:   app/app_usuarios/templates/back/user_update.html
	new file:   app/app_usuarios/templates/base_usuarios.html
	new file:   app/app_usuarios/templates/login.html
	new file:   app/app_usuarios/templates/logout-post.html
	new file:   app/app_usuarios/templates/logout.html
	new file:   app/app_usuarios/templates/password_change_form.html
	new file:   app/app_usuarios/templates/registration-org.html
	new file:   app/app_usuarios/templates/registration.html
	new file:   app/app_usuarios/templates/user_delete.html
	new file:   app/app_usuarios/templates/user_list.html
	new file:   app/app_usuarios/templates/user_update.html
	new file:   app/app_usuarios/tests.py
	new file:   app/app_usuarios/urls_onboarding.py
	new file:   app/app_usuarios/urls_user.py
	new file:   app/app_usuarios/views.py
	new file:   app/app_usuarios/views_onboarding.py
	new file:   app/appreportes/__init__.py
	new file:   app/appreportes/admin.py
	new file:   app/appreportes/apps.py
	new file:   app/appreportes/models.py
	new file:   app/appreportes/templates/base_reportes.html
	new file:   app/appreportes/templates/info_reportes.html
	new file:   app/appreportes/tests.py
	new file:   app/appreportes/urls.py
	new file:   app/appreportes/views.py
	new file:   app/ecuapassdocs/README.md
	new file:   app/ecuapassdocs/__init__.py
	new file:   app/ecuapassdocs/info/__init__.py
	new file:   app/ecuapassdocs/info/ecuapass_checking.py
	new file:   app/ecuapassdocs/info/ecuapass_cloud.py
	new file:   app/ecuapassdocs/info/ecuapass_data.py
	new file:   app/ecuapassdocs/info/ecuapass_exceptions.py
	new file:   app/ecuapassdocs/info/ecuapass_extractor.py
	new file:   app/ecuapassdocs/info/ecuapass_globals.py
	new file:   app/ecuapassdocs/info/ecuapass_info.py
	new file:   app/ecuapassdocs/info/ecuapass_info_AGENCOMEXCARGO.py
	new file:   app/ecuapassdocs/info/ecuapass_info_ALCOMEXCARGO.py
	new file:   app/ecuapassdocs/info/ecuapass_info_ALDIA.py
	new file:   app/ecuapassdocs/info/ecuapass_info_AUTOMOTORESDELNORTE.py
	new file:   app/ecuapassdocs/info/ecuapass_info_BYZA.py
	new file:   app/ecuapassdocs/info/ecuapass_info_CITRAPCAR.py
	new file:   app/ecuapassdocs/info/ecuapass_info_LOGITRANS.py
	new file:   app/ecuapassdocs/info/ecuapass_info_RODFRONTE.py
	new file:   app/ecuapassdocs/info/ecuapass_info_SANCHEZPOLO.py
	new file:   app/ecuapassdocs/info/ecuapass_info_TRANSCOMERINTER.py
	new file:   app/ecuapassdocs/info/ecuapass_info_cartaporte.py
	new file:   app/ecuapassdocs/info/ecuapass_info_declaracion.py
	new file:   app/ecuapassdocs/info/ecuapass_info_manifiesto.py
	new file:   app/ecuapassdocs/info/ecuapass_utils.py
	new file:   app/ecuapassdocs/info/others/ecuapass_info_cartaporte_BOTERO.py
	new file:   app/ecuapassdocs/info/others/ecuapass_info_cartaporte_SYTSA.py
	new file:   app/ecuapassdocs/info/others/ecuapass_info_manifiesto_BOTERO.py
	new file:   app/ecuapassdocs/info/others/ecuapass_info_manifiesto_SYTSA.py
	new file:   app/ecuapassdocs/info/resourceloader.py
	new file:   app/ecuapassdocs/info/retest.py
	new file:   app/ecuapassdocs/info/xmove-pycs.py
	new file:   app/ecuapassdocs/resources/__init__.py
	new file:   app/ecuapassdocs/resources/data_common/ciudades_paises_principales.txt
	new file:   app/ecuapassdocs/resources/data_common/ciudades_principales_colombia.txt
	new file:   app/ecuapassdocs/resources/data_common/ciudades_principales_ecuador.txt
	new file:   app/ecuapassdocs/resources/data_common/ciudades_principales_peru.txt
	new file:   app/ecuapassdocs/resources/data_common/join-ciudades-paises.py
	new file:   app/ecuapassdocs/resources/data_common/paises.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/__init__.py
	new file:   app/ecuapassdocs/resources/data_ecuapass/aduanas_colombia.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/aduanas_ecuador.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/aduanas_peru.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/aduanas_venezuela.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/ciudades-paises-colombia-ecuador.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/ciudades_bolivia.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/ciudades_colombia.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/ciudades_ecuador.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/ciudades_peru.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/ciudades_venezuela.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/condiciones_pago.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/condiciones_transporte.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/condiciones_unidadcarga.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/depositos_cebaf.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/depositos_huaquillas.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/depositos_loja.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/depositos_quito.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/depositos_tulcan.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/derivado.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/distritos.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/documentos.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/empresa.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/empresas_transporte.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/meses.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/monedas.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/paises.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/paises_todos.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/procedimientos.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/sectores.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/sustancias.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/tipos_carga.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/tipos_documento.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/tipos_embalaje.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/tipos_incoterm.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/tipos_sexo.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/tipos_unidadcarga.txt
	new file:   app/ecuapassdocs/resources/data_ecuapass/tipos_vehiculo.txt
	new file:   app/ecuapassdocs/resources/docs/__init__.py
	new file:   app/ecuapassdocs/resources/docs/cartaporte-contrato-BYZA.pdf
	new file:   app/ecuapassdocs/resources/docs/cartaporte-vacia-SILOG-BYZA.pdf
	new file:   app/ecuapassdocs/resources/docs/cartaporte-vacia-SILOG-BYZA.svg
	new file:   app/ecuapassdocs/resources/docs/ciudades-paises-colombia-ecuador.txt
	new file:   app/ecuapassdocs/resources/docs/coordinates_pdfs_docs_ALDIA.json
	new file:   app/ecuapassdocs/resources/docs/coordinates_pdfs_docs_CODEBIN.json
	new file:   app/ecuapassdocs/resources/docs/declaracion-vacia-NTA.pdf
	new file:   app/ecuapassdocs/resources/docs/fix-manifiesto-ENDMARK.py
	new file:   app/ecuapassdocs/resources/docs/image-cartaporte-vacia-SILOG-BYZA.png
	new file:   app/ecuapassdocs/resources/docs/image-declaracion-vacia-NTA.png
	new file:   app/ecuapassdocs/resources/docs/image-manifiesto-vacio-NTA-BYZA.png
	new file:   app/ecuapassdocs/resources/docs/input_parameters_cartaporte.json
	new file:   app/ecuapassdocs/resources/docs/input_parameters_declaracion.json
	new file:   app/ecuapassdocs/resources/docs/input_parameters_manifiesto.json
	new file:   app/ecuapassdocs/resources/docs/manifiesto-vacio-NTA-BYZA.pdf
	new file:   app/ecuapassdocs/resources/docs/manifiesto-vacio-NTA-BYZA.svg
	new file:   app/manage.py
	new file:   app/resources
	new file:   app/templates/_base_main_head.html
	new file:   app/templates/_base_main_sidebar.html
	new file:   app/templates/_command_buttons.html
	new file:   app/templates/base_main.html
	new file:   app/templates/base_page.html
	new file:   app/templates/documento_forma.html
	new file:   app/templates/documento_listado.html
	new file:   app/templates/documento_main.html
	new file:   app/templates/index.html
	new file:   app/templates/info_view.html
	new file:   app/templates/messages.html
	new file:   app/templates/onboarding/crear_empresa.html
	new file:   app/templates/onboarding/exito.html
	new file:   b
	new file:   db-scripts.py
	new file:   dbvars-lg.sh
	new file:   old-requirements.txt
	new file:   requirements.txt
	new file:   start_web.sh
	new file:   test.py
	new file:   tests/TEST-BYZA-CPI-CO7249-DOCFIELDS.json
	new file:   tests/TEST-BYZA-CPI-CO7249.pdf
	new file:   tests/cpis.log
	new file:   tests/db-create-UserAndDB.sh
	new file:   tests/db-functions.py
	new file:   tests/dblg.sh
	new file:   tests/pg.log
	new file:   tests/psql.sh

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.gitignore

